routes:
  - id: auth-service
    path: /auth/**
    uri: http://localhost:8081
    filters:
      - AuthFilter
      - LoggingFilter
  - id: user-service
    path: /user/**
    uri: lb://user-service
    filters:
      - RateLimitFilter